#### MACROS
CC      = gcc
MAKE    = make
LD	= ld
RM      = rm -f
INSTALL	= install
CP	= cp
CHGRP   = chgrp

KERNEL_PATH = /home/guiller/minipc/src/kernel/linux-2.6.20.1
KERNEL_PATH = /usr/src/linux-headers-3.2.0-4-common

INCPATH = -I.

CFLAGS = -Wall -O3 -pipe -D_REENTRANT -mcpu=athlon -O3 -pipe -fomit-frame-pointer -falign-functions=4 -falign-loops=4 -falign-jumps=4 -mpreferred-stack-boundary=2 -fexpensive-optimizations -fschedule-insns2 -fno-strict-aliasing -ffast-math -funroll-loops -fno-inline-functions
CFLAGS = -Wall -O3 -pipe -D_REENTRANT -O3 -pipe -fomit-frame-pointer -mpreferred-stack-boundary=2 -fexpensive-optimizations -fschedule-insns2 -fno-strict-aliasing -ffast-math -funroll-loops -fno-inline-functions

SRC = fileb.c channels.c \
	mydvb.c mydvb_tune.c \
	mydvb_info.c info_dvb.c \
	util.c tables.c \
	descriptor.c dynarray.c \
	mydvb_log.c \
	mhp_desc.c \
	mhp_tables.c

OBJ = $(SRC:.c=.o)


PREFIX = /usr/local

MYXINE_CONFIG_FILE = /etc/myxine.config

#### COMPILING

all: libmydvb.a

libmydvb.a: $(OBJ)
	ar -rc libmydvb.a $(OBJ)
	ranlib libmydvb.a


channels.o: channels.c channels.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o channels.o channels.c

fileb.o: fileb.c fileb.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o fileb.o fileb.c

util.o: util.c util.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o util.o util.c

tables.o: tables.c tables.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o tables.o tables.c

descriptor.o: descriptor.c descriptor.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o descriptor.o descriptor.c

mydvb.o: mydvb.c mydvb.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o mydvb.o mydvb.c

mydvb_tune.o: mydvb_tune.c mydvb_tune.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o mydvb_tune.o mydvb_tune.c

info_dvb.o: info_dvb.c info_dvb.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o info_dvb.o info_dvb.c
	
mydvb_info.o: mydvb_info.c mydvb_info.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o mydvb_info.o mydvb_info.c	
	
mydvb_log.o: mydvb_log.c mydvb_log.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o mydvb_log.o mydvb_log.c
	
mhp_desc.o: mhp_desc.c mhp_desc.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o mhp_desc.o mhp_desc.c	

mhp_tables.o: mhp_tables.c mhp_tables.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o mhp_tables.o mhp_tables.c	

dynarray.o: dynarray.c dynarray.h
	$(CC) -I${KERNEL_PATH}/include $(INCPATH) $(CFLAGS) -c -o dynarray.o dynarray.c



#### INSTALL
install:
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/bin
	$(INSTALL) -d $(DESTDIR)/etc
	$(INSTALL) -g root -o root -m 755 myxine $(DESTDIR)$(PREFIX)/bin
	$(INSTALL) -g root -o root -m 644 myxine.config $(DESTDIR)/etc
	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/myxine
	$(INSTALL) -g root -o root -m 644 fondo.png $(DESTDIR)$(PREFIX)/share/myxine

uninstall:
	$(RM) $(DESTDIR)$(PREFIX)/bin/myxine
	$(RM) $(DESTDIR)${PREFIX}/etc/myxine.config
	$(RM) $(DESTDIR)$(PREFIX)/share/myxine/fondo.png

#### Limpieza de archivos

clean: 
	$(RM) *.o
	$(RM) myxine 

#CLEANCOPY

cleancopy:
	$(RM) *~

